import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function generateBookingPDF(booking, history = []) {
    const doc = new jsPDF();

    // Header
    doc.setFillColor(10, 14, 26);
    doc.rect(0, 0, 210, 45, 'F');
    doc.setTextColor(6, 182, 212);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('SSAS', 15, 20);
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text('Smart & Secure Ambulance Services', 15, 28);
    doc.setFontSize(9);
    doc.text(`Invoice #${booking.booking_number}`, 15, 36);
    doc.setTextColor(241, 245, 249);
    doc.setFontSize(11);
    doc.text(`Status: ${booking.status || 'New'}`, 155, 20);
    doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 155, 28);

    // Booking Details
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Booking Details', 15, 55);

    autoTable(doc, {
        startY: 60,
        theme: 'grid',
        headStyles: { fillColor: [6, 182, 212], textColor: [255, 255, 255] },
        body: [
            ['Booking Number', booking.booking_number],
            ['Patient Name', booking.patient_name],
            ['Relative Name', booking.relative_name],
            ['Phone', booking.relative_phone],
            ['Email', booking.relative_email || 'N/A'],
            ['Hiring Date', booking.hiring_date],
            ['Hiring Time', booking.hiring_time],
            ['Ambulance Type', { 1: 'BLS', 2: 'ALS', 3: 'Non-Emergency', 4: 'Boat' }[booking.ambulance_type] || 'Unknown'],
            ['Address', `${booking.address}, ${booking.city}, ${booking.state}`],
            ['Status', booking.status || 'New'],
            ['Driver', booking.driver_name || 'Not Assigned'],
            ['Ambulance Reg', booking.ambulance_reg_no || 'Not Assigned'],
        ],
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
    });

    // Tracking History
    if (history.length > 0) {
        const y = doc.lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Tracking History', 15, y);

        autoTable(doc, {
            startY: y + 5,
            theme: 'striped',
            headStyles: { fillColor: [6, 182, 212] },
            head: [['Status', 'Remark', 'Date']],
            body: history.map(h => [h.status, h.remark, new Date(h.created_at).toLocaleString('en-IN')]),
        });
    }

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by SSAS - Smart & Secure Ambulance Services', 15, pageHeight - 10);
    doc.text(`Page 1`, 190, pageHeight - 10);

    doc.save(`SSAS-Booking-${booking.booking_number}.pdf`);
}

export function exportToCSV(data, filename = 'export') {
    if (!data || data.length === 0) return;

    const headers = Object.keys(data[0]);
    const csvRows = [
        headers.join(','),
        ...data.map(row => headers.map(h => {
            let val = row[h] ?? '';
            val = String(val).replace(/"/g, '""');
            return `"${val}"`;
        }).join(','))
    ];

    const blob = new Blob([csvRows.join('\n')], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.csv`;
    a.click();
    URL.revokeObjectURL(url);
}
